<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/03/14 14:26:26

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=Jobet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
